# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "centos/8"
    config.vm.box_version = "2011.0"

    config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
    end

    config.vm.provision "shell", path: "provision.sh"
end
