# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"
home = ENV['HOME']
diskpath = home + '/VirtualBox VMs/raid/'


MACHINES = {
 :hw2raid => {
       :box_name => "centos/7",
       :ip_addr => '192.168.56.5',
	   :disks => {
		   :sata1 => {
               :dfile => diskpath + 'sata1.vdi', # Указываем где будут лежать файлы наших дисков
		       :size => 250,
		       :port => 1
		   },
		   :sata2 => {
               :dfile => diskpath + '/sata2.vdi',
		       :size => 250, # Megabytes
		       :port => 2
		   },
		   :sata3 => {
               :dfile => diskpath + 'sata3.vdi',
		       :size => 500,
		       :port => 3
		   },
		   :sata4 => {
               :dfile => diskpath + 'sata4.vdi',
		       :size => 500,
		       :port => 4
		   },
		   :sata5 => {
               :dfile => diskpath + 'sata5.vdi',
		       :size => 250,
		       :port => 5
		   }
		}
 },
}


Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          
          # Отключаем проброс общей папки в ВМ
    	  box.vm.synced_folder ".", "/vagrant", disabled: true

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false

                  boxconfig[:disks].each do |dname, dconf|
                      unless File.exist?(dconf[:dfile])
                        vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                            needsController =  true
                  end

		  end

          if needsController == true
             vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
             boxconfig[:disks].each do |dname, dconf|
                 vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
             end
          end

      end

 	  	box.vm.provision "shell", path: "provision.sh"
  	  	box.vm.provision "shell", path: "mkraid.sh"

      end
  end
end

