# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "en_US.UTF-8"
home = ENV['HOME'] # Используем глобальную переменную $HOME
disks = home + '/VirtualBox VMs/hw3/'

MACHINES = {
 :lvm => {
       :box_name => "centos/7",
#       :box_version => "2004.01",
       :box_version => "1804.2",
       :ip_addr => '192.168.56.5',
	   :disks => {
		   :sata1 => {
               :dfile => disks + 'sata1.vdi', # Указываем где будут лежать файлы наших дисков
		       :size => 10240,
		       :port => 1
		   },
		   :sata2 => {
               :dfile => disks + 'sata2.vdi',
		       :size => 2048, # Megabytes
		       :port => 2
		   },
		   :sata3 => {
               :dfile => disks + 'sata3.vdi',
		       :size => 1024,
		       :port => 3
		   },
		   :sata4 => {
               :dfile => disks + 'sata4.vdi',
		       :size => 1024,
		       :port => 4
		   }
		}
 },
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|

        config.vm.define boxname do |box|

            box.vm.box = boxconfig[:box_name]
            box.vm.box_version = boxconfig[:box_version]
            box.vm.host_name = boxname.to_s
            box.vm.synced_folder ".", "/vagrant", disabled: true # Отключаем проброс общей папки в ВМ
            box.vm.network "private_network", ip: boxconfig[:ip_addr]

            box.vm.provider :virtualbox do |vb|

                vb.customize ["modifyvm", :id, "--memory", "1024"]

                vb.customize ["storagectl", :id, "--name", "SATA controller", "--add", "sata" ] #create SATA controller

                boxconfig[:disks].each do |dname, dconf|

                    unless File.exist?(dconf[:dfile])

                        #create disks, not fixed
                        vb.customize ['createmedium', '--filename', dconf[:dfile], '--size', dconf[:size], '--variant', 'Standard']

                        #attach Disks to SATA controller
        				vb.customize ['storageattach', :id,  '--storagectl', 'SATA controller', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]

                    end

                end

            end

 	        box.vm.provision "shell", inline: <<-SHELL
	            mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
	            yum install -y mdadm smartmontools hdparm gdisk lvm2 xfsdump
SHELL

        end

    end

end
